$("#syx").on("click",function(){
   console.log("ok");
   $("#xx").css("display","block");
   $("#lf").css("display","block");
})
$("#x1").change(function(){
    if($("#x1").val()=="1"){
       console.log("l")
       $("#x2").css("visibility","visible");
       $("#s2").css("visibility","visible");
       $("#pt").css("visibility","visible");
   }else{
    $("#x2").css("visibility","hidden");
    $("#s2").css("visibility","hidden");
    $("#pt").css("visibility","hidden");
   }
})
    //网页上所用到的点击切换
    $(".check").on("click",function(){
        console.log($(this).attr("data-index"));
        console.log($(".spte").eq(parseInt($(this).attr("data-index"))));
        console.log($(".spte"));
        if($(".spte").eq(parseInt($(this).attr("data-index"))).attr("data-wih")=="off"){
            $(".spte").eq(parseInt($(this).attr("data-index"))).attr("data-wih","ok");
            $(".spte").eq(parseInt($(this).attr("data-index"))).slideDown("show");
        }else{
            $(".spte").eq(parseInt($(this).attr("data-index"))).attr("data-wih","off");
            $(".spte").eq(parseInt($(this).attr("data-index"))).slideUp("hide");
        }
    })

